SELECT * FROM V$LOG;
SELECT * FROM V$LOGFILE;
ALTER DATABASE DROP LOGFILE MEMBER '/bbdd/grupo3-log2.log';
ALTER SYSTEM SWITCH LOGFILE;
ALTER DATABASE DROP LOGFILE MEMBER'/u01/app/oracle/oradata/ORCL/redo03.log';