/****

READ WRITE
READ ONLY
OFFLINE
    -NORMAL
    -TEMPORARY
    -IMMEDIATE
ONLINE
*/

ALTER TABLESPACE "VENTAS" READ ONLY;
ALTER TABLESPACE "VENTAS" READ WRITE;
ALTER TABLESPACE "VENTAS" OFFLINE NORMAL;
ALTER TABLESPACE "VENTAS" OFFLINE TEMPORARY;
ALTER TABLESPACE "VENTAS" OFFLINE IMMEDIATE;
ALTER TABLESPACE "VENTAS" ONLINE;


CREATE TABLE PR1 (CODIGO NUMBER) TABLESPACE VENTAS;
