CREATE TABLESPACE TBS2 DATAFILE '/home/oracle/bbdd/t4.dbf' SIZE 100m REUSE 
  EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;
  
--Crear Tabla
CREATE TABLE T10
(
  C1 VARCHAR2(50) 
) 
TABLESPACE TBS2 
STORAGE 
   ( INITIAL 100K);

DROP TABLE T10;


CREATE TABLE T11
(
  C1 VARCHAR2(50) 
) 
TABLESPACE TBS2 
STORAGE 
   ( INITIAL 4m);
  
   
   
SELECT * FROM DBA_SEGMENTS WHERE SEGMENT_NAME='T10';
SELECT * FROM DBA_EXTENTS WHERE SEGMENT_NAME='T10';

SELECT * FROM DBA_SEGMENTS WHERE SEGMENT_NAME='T11';
SELECT * FROM DBA_EXTENTS WHERE SEGMENT_NAME='T11';
