--Crear Tablespaces
CREATE TABLESPACE RRHH DATAFILE '/home/oracle/bbdd/rrhh.dbf'  size 10M;

CREATE TABLESPACE VENTAS DATAFILE '/home/oracle/bbdd/ventas.dbf' size 5M, '/home/oracle/bbdd/ventas2.dbf' size 10M;

CREATE TABLESPACE TBS1 DATAFILE '/home/oracle/bbdd/t3.dbf' SIZE 100m REUSE 
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
  
--AUTOALLOCATE   EXTENSIONES DE  64K, 1M, 8M, 64M
--UNIFORM   SIZE XM

--Crear Tabla
CREATE TABLE T3
(
  C1 VARCHAR2(50) 
) 
TABLESPACE TBS1 
STORAGE 
   ( INITIAL 100K);

drop table t3;

CREATE TABLE T4
(
  C1 VARCHAR2(50) 
) 
TABLESPACE TBS1 
STORAGE 
   ( INITIAL 2M);
   
   drop table t4;



CREATE TABLE T5
(
  C1 VARCHAR2(50) 
) 
TABLESPACE TBS1 
STORAGE 
   ( INITIAL 950K);
   
   drop table t4;


SELECT * FROM DBA_SEGMENTS WHERE SEGMENT_NAME='T3';
SELECT * FROM DBA_EXTENTS WHERE SEGMENT_NAME='T3';

SELECT * FROM DBA_SEGMENTS WHERE SEGMENT_NAME='T4';
SELECT * FROM DBA_EXTENTS WHERE SEGMENT_NAME='T4';

SELECT * FROM DBA_SEGMENTS WHERE SEGMENT_NAME='T5';
SELECT * FROM DBA_EXTENTS WHERE SEGMENT_NAME='T5';