CREATE TABLESPACE TBS3 DATAFILE '/home/oracle/bbdd/TBS3.dbf' SIZE 1M 
	AUTOEXTEND ON
	NEXT 1M
	MAXSIZE 250M;
DROP TABLESPACE TBS3;
CREATE TABLE AUTO1 (DATOS VARCHAR2(100))  STORAGE(INITIAL 500K) TABLESPACE TBS3;
INSERT INTO AUTO1 VALUES ('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA');
INSERT INTO AUTO1 SELECT * FROM AUTO1;
SELECT * FROM AUTO1;
DROP TABLE AUTO1;

ALTER DATABASE DATAFILE '/home/oracle/bbdd/TBS3.dbf' AUTOEXTEND OFF;
ALTER DATABASE DATAFILE '/home/oracle/bbdd/TBS3.dbf' AUTOEXTEND ON NEXT 1M  MAXSIZE 250M;


ALTER TABLESPACE TBS3 
    ADD DATAFILE '/home/oracle/bbdd/tbs3-2.dbf' SIZE 10M
      AUTOEXTEND ON
      NEXT 512K
      MAXSIZE 250M;
      
 ALTER DATABASE DATAFILE '/home/oracle/bbdd/TBS3.dbf'
   RESIZE 1M;