CREATE UNDO TABLESPACE UNDOTBS2 DATAFILE '/home/oracle/bbdd/undo2.dbf' size 100m  AUTOEXTEND on next 10m maxsize 250m;
SELECT * FROM DBA_TABLESPACES WHERE CONTENTS='UNDO';
SHOW PARAMETER UNDO;
ALTER SYSTEM SET UNDO_TABLESPACE= UNDOTBS2 SCOPE=BOTH;
UPDATE TRANSACCIONES SET DATOS='BBBB';
SELECT * FROM V$TRANSACTION;
SELECT * FROM DBA_DATA_FILES WHERE TABLESPACE_NAME='UNDOTBS2';
COMMIT;