CREATE TABLE TRANSACCIONES
( DATOS VARCHAR2(100));

INSERT INTO TRANSACCIONES VALUES('AAAAA');
SELECT * FROM V$TRANSACTION;--UBAFIL id del archivo en DBA_DATA_FILES
SELECT * FROM DBA_DATA_FILES;
COMMIT;
UPDATE TRANSACCIONES SET DATOS='BBBB';
INSERT INTO TRANSACCIONES VALUES ('CCCCC');
COMMIT;